### ISSUE TITLE
Update wizard results design

### ISSUE THREAD

**Issue by christiemolloy** [aerogear/mobile-developer-console#405]
@tiffanynolan to follow up here with recommended design approach for the wizard.

**Comment by tiffanynolan** [comment]
@christiemolloy Content is all set. Marvel handoff link which should have an easy way to copy/paste the text: https://marvelapp.com/4b4g0aa/screen/61087132/handoff

**Comment by christiemolloy** [comment]
closing this because PR was merged ^
